spring:
  thymeleaf:
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://121.251.255.96:3306/yibantest_lostandfound
    username: yibantest
    password: yibantest
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8085

yibanoauth:
  lostandfound:
    APPID: "2f803dad07f95108"
    APPkey: "f732a9b113713c3e1f85a85b6b1282b8"
    APPURL: "http://f.yiban.cn/iapp47291"
    name: "admin"
    password: "admin"